### ISSUE TITLE
Support for wagtail 1.5

### ISSUE THREAD

**Issue by fabiommendes** [springload/wagtailgmaps#10]
Have you tested it agaist Wagtail 1.5?

In my installation it shows the char input and no map appears. It loads only map-field.js, but it fails to insert a link to the google api.

**Comment by SalahAdDin** [comment]
Does it happen in `wagtail` 1.6?

**Comment by pyMan** [comment]
It's happening to me with wagtail 1.9

**Comment by SalahAdDin** [comment]
Try with `wagtailgeowidget` instead, I think is very good.

**Comment by thibaudcolas** [comment]
@pyMan we have a Wagtail 1.9 site running with this at https://github.com/springload/madewithwagtail/blob/4512a1faddae5570518bb7a7c9a3b411ab7245b2/madewithwagtail/settings/base.py#L83, could you compare this to your set up and report back on what is different?

**Comment by loicteixeira** [comment]
We've release v`0.3` and formalised which [versions are supported](https://github.com/springload/wagtailgmaps/tree/master/docs#pythondjangowagtail-support). Wagtail `1.5` isn't part of it but given this issue was quite old, I imagine this is no longer needed anymore.
