### ISSUE TITLE
Deprecate django-overextends requirement

### ISSUE THREAD

**Issue by SalahAdDin** [springload/wagtailgmaps#15]
Hi man

Thank you for this package!

I think that, as `django-overextends` requirement was deprecated in `wagtail`, can you deprecate here? 

Thanks!

**Comment by loicteixeira** [comment]
Will do. Thank you for raising this issue.

We should use Wagtail hooks rather than `django-overextends`. I think one of the PR is taking care of that but if it doesn't, I'll make sure to remove this dependency.

**Comment by loicteixeira** [comment]
Removed with #19.
