### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by emg36** [springload/wagtailgmaps#2]
<code>(ccba)Elliots-iMac:ccba elliotgilmore$ pip install wagtailgmaps

Downloading/unpacking wagtailgmaps

  Downloading wagtailgmaps-0.2.1.tar.gz

  Running setup.py egg_info for package wagtailgmaps

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/Users/Elliot/.virtualenvs/ccba/build/wagtailgmaps/setup.py", line 4, in <module>

        with open(os.path.join(os.path.dirname(__file__), 'README.md')) as readme:

    IOError: [Errno 2] No such file or directory: 

'/Users/Elliot/.virtualenvs/ccba/build/wagtailgmaps/README.md'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/Elliot/.virtualenvs/ccba/build/wagtailgmaps/setup.py", line 4, in <module>

    with open(os.path.join(os.path.dirname(__file__), 'README.md')) as readme:

IOError: [Errno 2] No such file or directory: '/Users/Elliot/.virtualenvs/ccba/build/wagtailgmaps/README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/Elliot/.virtualenvs/ccba/build/wagtailgmaps<code>

**Comment by jordij** [comment]
Hi, I've uploaded a new release fixing the error. Should be ok now.

Cheers
