### ISSUE TITLE
Entering the exact address (with street number)

### ISSUE THREAD

**Issue by scientist1642** [springload/wagtailgmaps#26]
Hi,
As I see the entered address with `longlat=false` gets formatted without the street number, I wonder why is it so? Thanks.

**Comment by loicteixeira** [comment]
Hi.

Unfortunately I'm not able to reproduce the error. With `wagtailgmaps==0.3.1` and `wagtail==1.13`. The street number doesn't get stripped when I input our address `7 Dixon Street, Te Aro, Wellington 6011, New Zealand` (nor does the building floor or company name when I set the whole address `Springload, Level 7, Hope Gibbons Building, 7 Dixon Street, Te Aro, Wellington 6011, New Zealand`).

Could you confirm:
- what versions of `wagtailgmap`, `wagtail` and `python` are installed
- which address you use
- when exactly does the address get stripped of its street number (e.g. as soon as you type or when you save the page or when displayed on the front-end).

Cheers.

**Comment by scientist1642** [comment]
I noticed that addresses I had problem with are not exactly on google maps and that causes the problem. I will use the  long-lat form for now. 
Thanks for the reply!
