### ISSUE TITLE
Map widget in admin system not loading on page load

### ISSUE THREAD

**Issue by scisteffan** [springload/wagtailgmaps#36]
In map-field-panel.js the initialise of the google map does not load because the window.load event binding happens inside document.ready, which is too late:

`$(document).ready(function() {google.maps.event.addDomListener(document, 'load', function() {`

Since it's already wrapped inside document.ready I removed google.maps.event.addDomListener and it fixed the issue.

**Comment by loicteixeira** [comment]
Nice catch @scisteffan. Would you might submitting a PR with the fix?

**Comment by loicteixeira** [comment]
It should be available on PyPi as 1.0.1 now. Thanks again.
