### ISSUE TITLE
google is not defined -> gmaps api not loaded?

### ISSUE THREAD

**Issue by ximarix** [springload/wagtailgmaps#5]
I have tried to embed wagtailgmaps into a fresh install of wagtail (latest, 1.1).

The address field ist displayed, however no map appears. My javascript console tells me, that google is not defined (map-field.js, line 3). 

I couldn't find anything in the changelogs of wagtail that might cause this. Aren't we missing something like this somewhere: <script src='https://maps.googleapis.com/maps/api/js?....'></script> ?

**Comment by jordij** [comment]
Hi @ximarix Make sure you include `wagtailgmaps` before all the `wagtail.*` apps in the `INSTALLED_APPS` definition of your `settings.py`.

**Comment by ximarix** [comment]
Great, solved, thank you @jordij!
