### ISSUE TITLE
wagtailgmaps and "snippets"

### ISSUE THREAD

**Issue by christiancabizza** [springload/wagtailgmaps#8]
Does this library work in both Pages and Snippets?
I'm trying to make it work into a Snippet and the Google Map does not appear...

**Comment by jordij** [comment]
Hi Christian. Yes it should work as long as your `FieldPanel` is nested in a `MultiFieldPanel` as mentioned somewhere in the docs.

Otherwise make sure  you include `wagtailgmaps` before all the `wagtail.*` apps in the `INSTALLED_APPS` definition of your `settings.py`.

**Comment by SalahAdDin** [comment]
@jordij Why?

Is needed put this in the lastest `wagtail` version?

**Comment by loicteixeira** [comment]
@christiancabizza I'm not too sure at the moment. I'll update you on that matter as soon as I get a change to look at it.

@SalahAdDin This was because the project overwrites some wagtail templates. This is no longer the case as of f490c0be7a2539da26b063bdd3c81e4b0315a7b4.

**Comment by loicteixeira** [comment]
This definitely works with snippets.

Example of an implementation we currently use:
```python
from django.db import models
from wagtail.wagtailsnippets.models import register_snippet
from wagtailgmaps.edit_handlers import MapFieldPanel

@register_snippet
class Location(models.Model):
    address = models.CharField(max_length=255, blank=True)

    panels = [
        MapFieldPanel('address', classname="gmap"),
    ]
```

**Comment by SalahAdDin** [comment]
@loicteixeira Oh, thank you!
